alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 3h
      routes:
      - match:
          severity: warning
        receiver: 'msteams-warning'
        continue: true
      - match:
          severity: critical
        receiver: 'msteams-critical'
    receivers:
    - name: 'msteams-warning'
      webhook_configs:
      - url: 'http://alertmanager-msteams:2000/'
        send_resolved: true
    - name: 'msteams-critical'
      webhook_configs:
      - url: 'http://alertmanager-msteams:2000/critical'
        send_resolved: true